### ISSUE TITLE
Can't setup train environment.

### ISSUE THREAD

**Issue by fuchun-wang** [youngkyunJang/Deep-Hash-Distillation#1]
Hi, I'm a fresh learner of hash, and just cloned your repo to my server.
Under the imagent-resnet setting, the code can not work.
It seems like need to resize imagenet's images to universal resolution first. Cause the images in orginal imagenet database has various resolution. And pytorch raise a exception when use your custom dataloader.
`stack expects each tensor to be equal size, but got [3, 375, 500] at entry 0 and [3, 427, 640] at entry 1`
By the way, your work is awesome!

**Comment by youngkyunJang** [comment]
Hi, Thanks for showing interests in our work!

It's a draft version, I will finalize the github soon!
