### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by jingzhang697** [youngkyunJang/Deep-Hash-Distillation#4]
Hello,
    Recently, I am deeply studying about image retrieval, and I want to exercise my ability through this code. I read it carefully and downloaded coco2014 according to the requirements of readme.md, but when I run train.py, many of the labels in. /data/txt are different from the image file names in datasets, showing that there is no file. I want to know how the code in labels is formed and can it be changed? In addition, I don't know which year to download ImageNet and NUS-WIDE datasets. I'm confused and don't know what to do. I hope I can get your help, thank you very much!

**Comment by youngkyunJang** [comment]
Hi! it is not organized & many papers use different experimental setups in this field.
I will share entire dataset & configuration within a week! Just keep track on this github :)

**Comment by youngkyunJang** [comment]
I have uploaded the dataset, so I close this issue!
